name: links
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * 1"  # 매주 월요일

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --cache
            --max-cache-age 1d
            --no-progress
            --exclude-loopback
            --accept '200,204,206,403,429'
            --timeout 20
            --max-retries 2
            --exclude-path '.git'
            --exclude-path 'node_modules'
            './**/*.md'
          fail: true
